/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basicwindow;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        ansLabel = new javax.swing.JLabel();
        timeButton = new javax.swing.JButton();
        forButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bilangan Pertama: ");

        jLabel2.setText("Bilangan Kedua: ");

        plusButton.setLabel("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setLabel("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        ansLabel.setText("Hasilnya adalah: ");

        timeButton.setText("x");
        timeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeButtonActionPerformed(evt);
            }
        });

        forButton.setText("/");
        forButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forButton))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusButton)
                    .addComponent(plusButton)
                    .addComponent(timeButton)
                    .addComponent(forButton))
                .addGap(29, 29, 29)
                .addComponent(ansLabel)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        int number1, number2;
        try {
            number1 = Integer.parseInt(
                    this.bil1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(
                    this.bil2.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int answer = number1 + number2;
        this.ansLabel.setText(
                "Hasilnya adalah: " + answer);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        int number1, number2;
        try {
            number1 = Integer.parseInt(
                    this.bil1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(
                    this.bil2.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int answer = number1 - number2;
        this.ansLabel.setText(
                "Hasilnya adalah: " + answer);
    }//GEN-LAST:event_minusButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        int number1, number2;
        try {
            number1 = Integer.parseInt(
                    this.bil1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(
                    this.bil2.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int answer = number1 * number2;
        this.ansLabel.setText(
                "Hasilnya adalah: " + answer);
    }//GEN-LAST:event_timeButtonActionPerformed

    private void forButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forButtonActionPerformed
        double number1, number2;
        try {
            number1 = Integer.parseInt(
                    this.bil1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(
                    this.bil2.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bilangan pertama salah",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double answer = number1 / number2;
        this.ansLabel.setText(
                "Hasilnya adalah: " + answer);
    }//GEN-LAST:event_forButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansLabel;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JButton forButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton timeButton;
    // End of variables declaration//GEN-END:variables
}
